version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql
    networks:
      - charlie
  
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/var/lib/redis
    networks:
      - charlie
  
  user_backend:
    image: user_backend
    build:
        context: ./
        dockerfile: ./docker/user/Dockerfile
        args:
          APPENV: 'local'
    ports:
        - '${APP_PORT:-4001}:4001'
    volumes:
        - './services/user/:/usr/src/app/'
    command: ["npm", "run", "start:dev"]
    networks:
        - charlie    

networks: 
    charlie:
        driver: bridge

volumes:
  db: 
    driver: local
  redis:
    driver: local