version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql
    networks:
      - charlie
  
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis:/var/lib/redis
    networks:
      - charlie
  
networks: 
    charlie:
        driver: bridge

volumes:
  db: 
    driver: local
  redis:
    driver: local